Repository jerryscript-project/jerryscript, pull requests merged in 2018-12, with the labels that each got.

#2607 Separate VM_OC_PROP_GET to a single operation in vm_loop
  jerry-core/vm/vm.c
Labels: enhancement, interpreter, performance

#2589 Improve the vm_loop suspending for exec operations
  jerry-core/jcontext/jcontext.h
  jerry-core/parser/js/byte-code.h
  jerry-core/vm/vm-defines.h
  jerry-core/vm/vm.c
  jerry-core/vm/vm.h
Labels: enhancement, interpreter, performance

#2606 Fix an issue while debugging with static snapshots
  jerry-core/vm/vm.c
Labels: bug, critical, debugger, snapshot

#2636 Fixed connection lost of debugging sessions
  jerry-ext/debugger/debugger-tcp.c
Labels: debugger

#2641 Rewrite debugger test runner to use portable redirect-and-append notation
  tools/runners/run-debugger-test.sh
Labels: debugger, test

#2644 Fix MbedOS build
  targets/mbedos5/Makefile.travis
Labels: critical, infrastructure

#2645 Ensure fresh Python 2.7 on Trusty and compatible Intervaltree
  .travis.yml
  targets/mbedos5/Makefile.travis
Labels: infrastructure
