Repository jerryscript-project/jerryscript, pull requests merged in 2018-05, with the labels that each got.

#2291 Rename the jerry_value_has_abort_flag function.
  docs/02.API-REFERENCE.md
  jerry-core/api/jerry.c
  jerry-core/include/jerryscript-core.h
  tests/unit-core/test-abort.c
Labels: api

#2312 Fix documentation of port API
  docs/05.PORT-API.md
  jerry-core/include/jerryscript-port.h
Labels: documentation, jerry-port

#2309 Update the 'README.md' of the JerryScript profiles.
  docs/01.GETTING-STARTED.md
  jerry-core/profiles/README.md
Labels: documentation

#2321 Setup SonarQube analysis in Travis CI
  .travis.yml
  sonar-project.properties
Labels: enhancement, test

#2316 Simplify code paths within PARSER_DUMP_BYTE_CODE
  jerry-core/parser/js/js-parser-statm.c
  jerry-core/parser/js/js-parser-util.c
  jerry-core/parser/js/js-parser.c
Labels: parser

#2322 Followup fix for SonarQube setup
  .travis.yml
Labels: bug

#2326 Remove usage of comma operator in array prototype
  jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c
Labels: bug

#2330 Use ecma_number_t instead of double where possible
  jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c
  jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c
  jerry-core/ecma/operations/ecma-arraybuffer-object.c
Labels: ecma builtins

#2333 Move (almost all) Travis CI jobs to container-based infrastructure
  .travis.yml
  targets/esp8266/Makefile.travis
  targets/mbed/Makefile.mbed
  targets/mbed/Makefile.travis
  targets/mbed/cmake
  targets/nuttx-stm32f4/Makefile.travis
  targets/riot-stm32f4/Makefile.travis
  targets/zephyr/Makefile.travis
Labels: infrastructure

#2335 Revert the Mbed Travis CI job to sudo-based VM to avoid sporadic OOMs
  .travis.yml
Labels: infrastructure

#2334 Update the webpage
  01.GETTING-STARTED.md
  02.API-REFERENCE.md
  03.API-EXAMPLE.md
  05.PORT-API.md
  06.REFERENCE-COUNTING.md
  07.DEBUGGER.md
  09.EXT-REFERENCE-ARG.md
  10.EXT-REFERENCE-HANDLER.md
  12.EXT-REFERENCE-MODULE.md
Labels: documentation

#2324 Update Doxygen config file and fix Doxygen warnings
  Doxyfile
  jerry-core/api/jerry.c
  jerry-core/ecma/base/ecma-gc.c
  jerry-core/ecma/base/ecma-helpers-conversion.c
  jerry-core/ecma/base/ecma-helpers-errol.c
  jerry-core/ecma/base/ecma-helpers-number.c
  jerry-core/ecma/base/ecma-helpers-string.c
  jerry-core/ecma/base/ecma-helpers-value.c
  jerry-core/ecma/base/ecma-helpers.c
  jerry-core/ecma/builtin-objects/ecma-builtin-global.c
  jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-object.c
  jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtins.c
  jerry-core/ecma/operations/ecma-conversion.c
  jerry-core/ecma/operations/ecma-exceptions.c
  jerry-core/ecma/operations/ecma-function-object.c
  jerry-core/ecma/operations/ecma-jobqueue.c
  jerry-core/ecma/operations/ecma-objects.c
  jerry-core/ecma/operations/ecma-regexp-object.c
  jerry-core/jmem/jmem-heap.c
  jerry-core/jmem/jmem-poolman.c
  jerry-core/parser/js/byte-code.c
  jerry-core/parser/js/js-lexer.c
  jerry-core/parser/js/js-parser-statm.c
  jerry-core/parser/js/js-parser-util.c
  jerry-core/parser/js/js-parser.c
  jerry-core/vm/vm.c
Labels: bug, documentation

#2329 Remove legacy jerry_get_memory_limits API function and unused configuration macros
  docs/02.API-REFERENCE.md
  jerry-core/api/jerry.c
  jerry-core/config.h
  jerry-core/ecma/operations/ecma-lex-env.c
  jerry-core/include/jerryscript-core.h
  jerry-core/vm/vm-stack.h
Labels: api

#2339 Simplify run-time feature checks in unit tests
  tests/unit-core/test-arraybuffer.c
  tests/unit-core/test-promise.c
  tests/unit-core/test-typedarray.c
Labels: test

#2341 Add AppVeyor badge to readme
  README.md
Labels: documentation, infrastructure

#2346 Don't let doctests pollute the source tree
  .gitignore
  tests/unit-doc/CMakeLists.txt
Labels: test

#2347 Fix cmakelists of doctests to run generation only once
  tests/unit-doc/CMakeLists.txt
Labels: test

#2345 Fix heap buffer overflow in lit_utf_incr
  jerry-core/parser/regexp/re-parser.c
  tests/jerry/fail/regression-test-issue-2344.js
Labels: bug

#2342 Cleanup code around JERRY_UNREACHABLEs
  jerry-core/api/jerry-snapshot.c
  jerry-core/api/jerry.c
  jerry-core/ecma/base/ecma-gc.c
  jerry-core/ecma/base/ecma-helpers-string.c
  jerry-core/ecma/base/ecma-helpers-value.c
  jerry-core/ecma/base/ecma-helpers.c
  jerry-core/ecma/base/ecma-lcache.c
  jerry-core/ecma/base/ecma-property-hashmap.c
  jerry-core/ecma/builtin-objects/ecma-builtin-date-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-global.c
  jerry-core/ecma/builtin-objects/ecma-builtin-helpers-date.c
  jerry-core/ecma/builtin-objects/ecma-builtin-json.c
  jerry-core/ecma/builtin-objects/ecma-builtins.c
  jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-helpers.c
  jerry-core/ecma/operations/ecma-exceptions.c
  jerry-core/ecma/operations/ecma-objects-general.c
  jerry-core/ecma/operations/ecma-objects.c
  jerry-core/ecma/operations/ecma-regexp-object.c
  jerry-core/ecma/operations/ecma-typedarray-object.c
  jerry-core/jmem/jmem-poolman.c
  jerry-core/lit/lit-magic-strings.c
  jerry-core/lit/lit-strings.c
  jerry-core/vm/vm-stack.c
  jerry-core/vm/vm.c
Labels: ecma core

#2359 Update the webpage
  02.API-REFERENCE.md
Labels: documentation

#2352 Fix heap buffer overflow in re_parse_char_class
  jerry-core/parser/regexp/re-parser.c
  tests/jerry/regression-test-issue-2230.js
  tests/jerry/regression-test-issue-2237.js
Labels: bug

#2361 Simplify the AppVeyor configuration file
  appveyor.yml
Labels: infrastructure

#2362 Maintenance and merging of Valgrind and Valgrind-Freya code paths
  jerry-core/CMakeLists.txt
  jerry-core/jcontext/jcontext.h
  jerry-core/jmem/jmem-allocator-internal.h
  jerry-core/jmem/jmem-heap.c
  jerry-core/jmem/jmem-poolman.c
  tools/build.py
  tools/run-tests.py
Labels: memory management

#2364 Remove duplications from test runner
  tools/run-tests.py
Labels: test, tools
