Repository jerryscript-project/jerryscript, pull requests merged in 2018-02, with the labels that each got.

#2206 Update the webpage
  02.API-REFERENCE.md
Labels: documentation

#2208 Fix '--cmake-param' option of the build script.
  tools/build.py
Labels: bug, tools

#2209 Fix assertion in 're_insert_simple_iterator'
  jerry-core/parser/regexp/re-compiler.c
  jerry-core/parser/regexp/re-parser.c
  tests/jerry/regression-test-issue-2198.js
  tests/jerry/regression-test-issue-2204.js
Labels: bug, ecma builtins

#2218 Reduce the memory footprint of 'ecma_instantiate_builtin'
  jerry-core/ecma/builtin-objects/ecma-builtins.c
Labels: binary size, enhancement

#2214 Modified ecma string to utf8 string conversion to reduce binary size.
  jerry-core/ecma/base/ecma-helpers-string.c
  jerry-core/ecma/base/ecma-helpers.h
Labels: binary size, enhancement
