Repository jerryscript-project/jerryscript, pull requests merged in 2019-06, with the labels that each got.

#2871 Implement the for of statement
  jerry-core/config.h
  jerry-core/include/jerryscript-snapshot.h
  jerry-core/parser/js/byte-code.h
  jerry-core/parser/js/js-lexer.h
  jerry-core/parser/js/js-parser-scanner.c
  jerry-core/parser/js/js-parser-statm.c
  jerry-core/parser/js/js-parser-util.c
  jerry-core/parser/js/js-parser.h
  jerry-core/profiles/README.md
  jerry-core/vm/vm-stack.c
  jerry-core/vm/vm-stack.h
  jerry-core/vm/vm.c
  jerry-core/vm/vm.h
  tests/jerry/es2015/for-of.js
  tests/unit-core/test-snapshot.c
Labels: ES2015

#2898 Integrate LLVM's libfuzzer engine with JerryScript
  CMakeLists.txt
  docs/01.GETTING-STARTED.md
  jerry-main/CMakeLists.txt
  jerry-main/libfuzzer.c
  tools/build.py
Labels: feature request

#2899 Add missing release value call for opfunc_addition
  jerry-core/vm/opcodes-ecma-arithmetics.c
  tests/jerry/fail/regression-test-issue-2894.js
  tests/jerry/fail/regression-test-issue-2897.js
Labels: bug

#2907 Correctly propagate errors when parsing modules
  jerry-core/ecma/base/ecma-module.c
  jerry-core/ecma/base/ecma-module.h
  tests/jerry/fail/regression-test-issue-2896.js
Labels: ES2015, bug

#2916 Improve libfuzz integration
  CMakeLists.txt
  docs/01.GETTING-STARTED.md
  jerry-main/CMakeLists.txt
  jerry-main/libfuzzer.c
Labels: test

#2904 Implement String repeat
  jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.inc.h
  jerry-core/lit/lit-magic-strings.inc.h
  jerry-core/lit/lit-magic-strings.ini
  tests/jerry/es2015/string-prototype-repeat.js
Labels: ES2015

#2915 Improve JS object native pointer unit test
  tests/unit-core/test-api.c
Labels: test

#2918 Make libfuzzer driver properly handle ES2015 test inputs with Promises
  jerry-main/libfuzzer.c
Labels: test

#2886 Reduce the size of vm_frame_ctx_t
  jerry-core/vm/vm-defines.h
  jerry-core/vm/vm.c
Labels: memory consumption

#2919 Fix allocation problems when using import and export
  jerry-core/parser/js/js-parser-module.c
  tests/jerry/fail/regression-test-issue-2908-1.js
  tests/jerry/fail/regression-test-issue-2908-2.js
  tests/jerry/fail/regression-test-issue-2908-3.js
  tests/jerry/fail/regression-test-issue-2908-4.js
Labels: ES2015, bug

#2921 Resolve build error after #2888
  jerry-core/vm/vm-defines.h
  jerry-core/vm/vm.c
Labels: critical

#2920 Module sources should be parsed in strict mode
  jerry-core/ecma/base/ecma-module.c
  tests/jerry/es2015/module-export-07.js
  tests/jerry/es2015/module-import-01.js
  tests/jerry/es2015/module-import-04.js
Labels: ES2015, bug

#2917 Ensure that the constructed object in [[Set]] operation with primitive base cannot be extensible
  jerry-core/vm/vm.c
  tests/jerry/regression-test-issue-2914.js
Labels: bug, interpreter

#2913 Container object's properties must be marked during GC.
  jerry-core/ecma/base/ecma-gc.c
  tests/jerry/es2015/regression-test-issue-2895.js
  tests/jerry/es2015/regression-test-issue-2911.js
Labels: ES2015, bug

#2893 Implement Array/TypedArray find index
  jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.inc.h
  jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c
  jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.inc.h
  jerry-core/lit/lit-magic-strings.inc.h
  jerry-core/lit/lit-magic-strings.ini
  tests/jerry/es2015/array-prototype-find-index.js
  tests/jerry/es2015/typedArray-find-index.js
Labels: ES2015, ecma builtins

#2882 Implement the Map/Set iterator operations
  jerry-core/ecma/base/ecma-gc.c
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/ecma/base/ecma-helpers-string.c
  jerry-core/ecma/base/ecma-helpers.h
  jerry-core/ecma/builtin-objects/ecma-builtin-array-iterator-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-map-iterator-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-map-iterator-prototype.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-map-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-map-prototype.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-map.c
  jerry-core/ecma/builtin-objects/ecma-builtin-set-iterator-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-set-iterator-prototype.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-set-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-set-prototype.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-set.c
  jerry-core/ecma/builtin-objects/ecma-builtins.inc.h
  jerry-core/ecma/operations/ecma-container-object.c
  jerry-core/ecma/operations/ecma-container-object.h
  jerry-core/ecma/operations/ecma-iterator-object.c
  jerry-core/ecma/operations/ecma-objects.c
  jerry-core/lit/lit-magic-strings.inc.h
  jerry-core/lit/lit-magic-strings.ini
  tests/jerry/es2015/map-iterators.js
  tests/jerry/es2015/set-iterators.js
Labels: ES2015

#2923 Update the internals documentation
  docs/04.INTERNALS.md
  docs/img/ecma_object.png
  docs/img/ecma_value.png
Labels: documentation

#2929 Hide info about --libfuzzer in tools/build.py behind --devhelp
  tools/build.py
Labels: minor, tools
