Repository jerryscript-project/jerryscript, pull requests merged in 2019-05, with the labels that each got.

#2860 Fixed typo in parser
  jerry-core/parser/js/js-parser.c
Labels: minor

#2859 Clear top module context after local variables have been imported
  jerry-core/vm/vm.c
  tests/jerry/es2015/module-import-04.js
Labels: ES2015, bug

#2862 Fixed linker issues of handle scope in jerry-ext on Windows platform.
  jerry-ext/handle-scope/handle-scope-allocator.c
Labels: bug

#2865 Fixed build issues with ES2015 subset profile on Windows.
  jerry-core/ecma/operations/ecma-dataview-object.c
Labels: ES2015, bug

#2864 Add NuttX specific port implementation.
  targets/nuttx-stm32f4/Makefile
  targets/nuttx-stm32f4/Makefile.travis
  targets/nuttx-stm32f4/jerry_main.c
  targets/nuttx-stm32f4/jerry_port.c
Labels: infrastructure

#2861 Implement path normalization in port-default
  jerry-port/default/default-io.c
Labels: ES2015, jerry-port

#2856 undefined byteLength should be treated 0 in DataView constructor
  jerry-core/ecma/operations/ecma-dataview-object.c
  tests/jerry/es2015/regression-test-issue-2854.js
Labels: ES2015, bug

#2863 Super parsing options should be set only in direct eval call
  jerry-core/ecma/builtin-objects/ecma-builtin-global.c
  jerry-core/ecma/operations/ecma-eval.c
  tests/jerry/fail/regression-test-issue-2846.js
Labels: ES2015, bug

#2870 Support external context in the snapshot tool
  jerry-main/main-unix-snapshot.c
  jerry-main/main-unix.c
Labels: bug, snapshot

#2874 Fix ecma collection header deallocation
  jerry-core/ecma/base/ecma-helpers-values-collection.c
Labels: bug, memory management

#2875 Properly release property name collection in for-in opcode handler
  jerry-core/vm/opcodes.c
  jerry-core/vm/vm.c
Labels: bug, memory management

#2872 Fix heap limit calculation when using the system allocator.
  jerry-core/jmem/jmem-heap.c
Labels: bug, memory management

#2881 Fixed 'C4028' compiler warnings.
  jerry-core/api/jerry.c
  jerry-core/ecma/base/ecma-module.h
Labels: bug

#2888 Cleanup unused macros/typedefs from ecma-globals and the vm
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/vm/vm-defines.h
  jerry-core/vm/vm-stack.h
Labels: minor

#2887 Add missing error check for ecma_regexp_exec_helper
  jerry-core/ecma/operations/ecma-regexp-object.c
  tests/jerry/fail/regression-test-issue-2885.js
Labels: bug

#2873 Implement the string iterators
  jerry-core/ecma/base/ecma-gc.c
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/ecma/base/ecma-helpers-string.c
  jerry-core/ecma/base/ecma-helpers.h
  jerry-core/ecma/builtin-objects/ecma-builtin-array-iterator-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-string-iterator-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-string-iterator-prototype.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtins.inc.h
  jerry-core/ecma/operations/ecma-iterator-object.c
  jerry-core/ecma/operations/ecma-objects.c
  jerry-core/lit/lit-magic-strings.inc.h
  jerry-core/lit/lit-magic-strings.ini
  tests/jerry/es2015/string-iterator.js
Labels: ES2015

#2890 Fix rounding issue in ecma_utf8_string_to_number
  jerry-core/ecma/base/ecma-helpers-conversion.c
  tests/jerry/arithmetics-bignums.js
  tests/jerry/regression-test-issue-2802.js
Labels: bug
