Repository jerryscript-project/jerryscript, pull requests merged in 2019-08, with the labels that each got.

#2981 Reduce the size of the jerry_context_t structure
  jerry-core/api/jerry.c
  jerry-core/ecma/base/ecma-gc.c
  jerry-core/ecma/builtin-objects/ecma-builtins.c
  jerry-core/ecma/operations/ecma-lex-env.c
  jerry-core/jcontext/jcontext.h
Labels: binary size

#2998 Add realloc function to jmem
  jerry-core/jmem/jmem-heap.c
  jerry-core/jmem/jmem.h
  tests/unit-core/test-jmem.c
Labels: memory management

#3008 Speed-up Travis builds
  .travis.yml
  tools/run-tests.py
Labels: infrastructure

#3015 Fix Zephyr build on Travis
  targets/zephyr/Makefile.travis
Labels: critical, infrastructure

#3018 Update Zephyr build on Travis
  targets/zephyr/Makefile.travis
Labels: critical, infrastructure

#3017 Don't run Coverity as the last task on Travis
  .travis.yml
Labels: infrastructure

#2999 Add string builder helper
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/ecma/base/ecma-helpers-string.c
  jerry-core/ecma/base/ecma-helpers.h
  tests/unit-core/test-stringbuilder.c
Labels: ecma builtins

#3020 Introduce CBC_MOV_IDENT opcode to improve performance
  jerry-core/parser/js/byte-code.h
  jerry-core/parser/js/js-parser.c
  jerry-core/vm/vm.c
  jerry-core/vm/vm.h
Labels: enhancement, interpreter, performance

#3006 Eliminate ECMA_TRY_CATCH macros part I.
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/ecma/base/ecma-helpers-string.c
  jerry-core/ecma/base/ecma-helpers.h
  jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
  jerry-core/ecma/builtin-objects/ecma-builtin-helpers.h
  jerry-core/ecma/operations/ecma-objects.c
  jerry-core/ecma/operations/ecma-objects.h
  tools/run-tests.py
Labels: binary size, ecma builtins

#3013 Fix building with build.py on Windows
  tests/unit-doc/CMakeLists.txt
  tools/build.py
  tools/gen-doctest.py
Labels: infrastructure

#3014 New trim helper function
  jerry-core/ecma/base/ecma-helpers-conversion.c
  jerry-core/ecma/base/ecma-helpers-string.c
  jerry-core/ecma/base/ecma-helpers.h
  jerry-core/ecma/builtin-objects/ecma-builtin-global.c
Labels: binary size, ecma builtins

#3019 General optimizations around compressed pointer management
  jerry-core/api/jerry.c
  jerry-core/debugger/debugger.c
  jerry-core/ecma/base/ecma-gc.c
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/ecma/base/ecma-helpers-values-collection.c
  jerry-core/ecma/base/ecma-helpers.c
  jerry-core/ecma/base/ecma-helpers.h
  jerry-core/ecma/base/ecma-property-hashmap.c
  jerry-core/ecma/base/ecma-property-hashmap.h
  jerry-core/ecma/builtin-objects/ecma-builtin-object.c
  jerry-core/ecma/builtin-objects/ecma-builtins.c
  jerry-core/ecma/operations/ecma-exceptions.c
  jerry-core/ecma/operations/ecma-function-object.c
  jerry-core/ecma/operations/ecma-get-put-value.c
  jerry-core/ecma/operations/ecma-objects-general.c
  jerry-core/ecma/operations/ecma-objects.c
  jerry-core/ecma/operations/ecma-reference.c
  jerry-core/ecma/operations/ecma-typedarray-object.c
  jerry-core/vm/opcodes.c
  jerry-core/vm/vm-stack.c
  jerry-core/vm/vm.c
Labels: binary size, ecma core, enhancement, performance

#2972 Number routines
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/ecma/builtin-objects/ecma-builtin-number.c
  jerry-core/ecma/builtin-objects/ecma-builtin-number.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtins-internal.h
  jerry-core/ecma/builtin-objects/ecma-builtins.c
  jerry-core/lit/lit-magic-strings.inc.h
  jerry-core/lit/lit-magic-strings.ini
  tests/jerry/es2015/number-isfinite.js
  tests/jerry/es2015/number-isinteger.js
  tests/jerry/es2015/number-isnan.js
  tests/jerry/es2015/number-issafeinteger.js
Labels: ES2015, ecma builtins

#3007 Optimize ecma_builtin_helper_def_prop
  jerry-core/api/jerry.c
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/ecma/base/ecma-helpers.c
  jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
  jerry-core/ecma/builtin-objects/ecma-builtin-helpers.h
  jerry-core/ecma/builtin-objects/ecma-builtin-json.c
  jerry-core/ecma/builtin-objects/ecma-builtin-object.c
  jerry-core/ecma/builtin-objects/ecma-builtin-promise.c
  jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.c
  jerry-core/ecma/operations/ecma-array-object.c
  jerry-core/ecma/operations/ecma-array-object.h
  jerry-core/ecma/operations/ecma-conversion.c
  jerry-core/ecma/operations/ecma-iterator-object.c
  jerry-core/ecma/operations/ecma-lex-env.c
  jerry-core/ecma/operations/ecma-objects-arguments.c
  jerry-core/ecma/operations/ecma-objects-arguments.h
  jerry-core/ecma/operations/ecma-objects-general.c
  jerry-core/ecma/operations/ecma-objects-general.h
  jerry-core/ecma/operations/ecma-objects.c
  jerry-core/ecma/operations/ecma-objects.h
  jerry-core/ecma/operations/ecma-regexp-object.c
  jerry-core/ecma/operations/ecma-typedarray-object.c
Labels: enhancement, performance

#3024 Adding a switch to the jerry-snapshot tool to load a function
  jerry-main/main-unix-snapshot.c
Labels: snapshot

#3021 Look up the previous block again after a GC in jmem_heap_realloc_block
  jerry-core/jmem/jmem-heap.c
Labels: bug, memory management

#3025 Add missing Valgrind macros to jmem
  jerry-core/jmem/jmem-allocator-internal.h
  jerry-core/jmem/jmem-heap.c
Labels: bug, memory management

#2938 Add indexOf and lastIndexOf function to typedArray
  jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-arraybuffer-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
  jerry-core/ecma/builtin-objects/ecma-builtin-helpers.h
  jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.c
  jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c
  jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.inc.h
  jerry-core/lit/lit-magic-strings.inc.h
  tests/jerry/es2015/typedarray-prototype-indexof.js
  tests/jerry/es2015/typedarray-prototype-lastindexof.js
Labels: ES2015, ecma builtins

#3016 Improve ecma_string_t descriptor
  jerry-core/ecma/base/ecma-alloc.c
  jerry-core/ecma/base/ecma-alloc.h
  jerry-core/ecma/base/ecma-gc.c
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/ecma/base/ecma-helpers-string.c
  jerry-core/ecma/base/ecma-helpers-value.c
  jerry-core/ecma/base/ecma-helpers.h
  jerry-core/ecma/base/ecma-literal-storage.c
  jerry-core/ecma/builtin-objects/ecma-builtin-symbol.c
  jerry-core/ecma/builtin-objects/ecma-builtins.c
  jerry-core/ecma/operations/ecma-container-object.c
  jerry-core/ecma/operations/ecma-symbol-object.c
  jerry-core/jcontext/jcontext.h
  jerry-core/lit/lit-globals.h
  jerry-core/parser/js/js-parser-module.c
Labels: ecma core, enhancement

#3028 Implement fast access mode arrays
  jerry-core/debugger/debugger.c
  jerry-core/ecma/base/ecma-gc.c
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/ecma/base/ecma-helpers.c
  jerry-core/ecma/base/ecma-helpers.h
  jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
  jerry-core/ecma/builtin-objects/ecma-builtin-object.c
  jerry-core/ecma/builtin-objects/ecma-builtins.c
  jerry-core/ecma/operations/ecma-array-object.c
  jerry-core/ecma/operations/ecma-array-object.h
  jerry-core/ecma/operations/ecma-objects-general.c
  jerry-core/ecma/operations/ecma-objects.c
  jerry-core/vm/vm-utils.c
  jerry-core/vm/vm.c
  tests/debugger/do_variables.expected
Labels: ecma core, enhancement, memory consumption, performance
