Repository jerryscript-project/jerryscript, pull requests merged in 2019-07, with the labels that each got.

#2932 Make API unavailable while processing native free callbacks
  docs/02.API-REFERENCE.md
  jerry-core/api/jerry.c
  jerry-core/ecma/base/ecma-gc.c
Labels: api, documentation

#2940 Add issue template for bug reports
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: infrastructure

#2942 Add pull request template
  .github/pull_request_template.md
Labels: infrastructure

#2939 CBC_PUSH_THIS_LITERAL must be converted back to CBC_PUSH_THIS during emitting unary lvalue opcode
  jerry-core/parser/js/js-parser-expr.c
  tests/jerry/regression-test-issue-2937.js
Labels: bug, parser

#2935 Limit the call stack size for native/builtin functions as well
  jerry-core/CMakeLists.txt
  jerry-core/config.h
  jerry-core/ecma/base/ecma-init-finalize.c
  jerry-core/ecma/operations/ecma-function-object.c
  jerry-core/jcontext/jcontext.h
  jerry-core/vm/vm.c
  tests/jerry/regression-test-issue-2905.js
  tests/jerry/vm-recursion-limit.js
  tools/build.py
  tools/run-tests.py
Labels: ecma core

#2944 Improve gen-unicode.py to support unicode ranges
  jerry-core/lit/lit-unicode-ranges.inc.h
  tests/jerry/regression-test-issue-2936.js
  tools/gen-unicode.py
Labels: bug, parser

#2955 Fix URLs in the repository after organization switch
  .travis.yml
  CONTRIBUTING.md
  README.md
  docs/01.GETTING-STARTED.md
  docs/03.API-EXAMPLE.md
  jerry-core/libjerry-core.pc.in
  jerry-debugger/README.md
  jerry-ext/libjerry-ext.pc.in
  jerry-libm/libjerry-libm.pc.in
  jerry-port/default/libjerry-port-default-minimal.pc.in
  jerry-port/default/libjerry-port-default.pc.in
  sonar-project.properties
  targets/nuttx-stm32f4/README.md
  targets/tizenrt-artik053/README.md
  tools/check-sonarqube.sh
Labels: documentation

#2926 Implement String startsWith/includes/endsWith
  jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
  jerry-core/ecma/builtin-objects/ecma-builtin-helpers.h
  jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.inc.h
  jerry-core/lit/lit-magic-strings.inc.h
  jerry-core/lit/lit-magic-strings.ini
  tests/jerry/es2015/string-prototype-endswith.js
  tests/jerry/es2015/string-prototype-includes.js
  tests/jerry/es2015/string-prototype-startswith.js
Labels: ES2015, ecma builtins

#2952 Update and improve API documentation
  docs/02.API-REFERENCE.md
Labels: documentation

#2958 Add missing release value call to %TypedArray%.prototype.findIndex routine
  jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c
  tests/jerry/es2015/regression-test-issue-2947.js
Labels: ES2015, bug

#2959 Fix the repeat count checking in String.prototype.repeat
  jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.c
  tests/jerry/es2015/regression-test-issue-2948.js
Labels: ES2015, bug

#2960 This argument must be pseudo-array in {Map/Set}Iterator.prototype.next routine
  jerry-core/ecma/operations/ecma-container-object.c
  tests/jerry/es2015/regression-test-issue-2950.js
Labels: ES2015, bug

#2961 Container object's internal object must be allocated firstly
  jerry-core/ecma/base/ecma-gc.c
  jerry-core/ecma/operations/ecma-container-object.c
  jerry-core/ecma/operations/ecma-container-object.h
  tests/jerry/es2015/regression-test-issue-2951.js
Labels: ES2015, bug

#2941 Include file path in Syntax error messages
  jerry-core/api/jerry.c
  jerry-core/ecma/base/ecma-module.c
  jerry-core/ecma/builtin-objects/ecma-builtin-function.c
  jerry-core/ecma/operations/ecma-eval.c
  jerry-core/jcontext/jcontext.h
  jerry-core/lit/lit-magic-strings.inc.h
  jerry-core/lit/lit-magic-strings.ini
  jerry-core/parser/js/js-parser.c
  jerry-main/main-unix.c
  targets/nuttx-stm32f4/jerry_main.c
  targets/tizenrt-artik053/apps/jerryscript/jerry_main.c
  tests/unit-core/test-api.c
Labels: ES2015

#2974 Fix mbedos5 build on Travis
  targets/mbedos5/tools/requirements.txt
Labels: critical, infrastructure

#2973 Fix Lcache and property hashmap related build option tests
  tools/run-tests.py
Labels: tools

#2970 Improve class literal parsing
  jerry-core/parser/js/js-parser-expr.c
  tests/jerry/es2015/class-get-set-as-method.js
Labels: ES2015, bug

#2971 Improve RegExp.prototype.compile
  jerry-core/ecma/builtin-objects/ecma-builtin-regexp-prototype.c
  tests/jerry/es2015/regression-test-issue-612.js
  tests/jerry/regexp-routines.js
  tests/jerry/regression-test-issue-1065.js
  tests/jerry/regression-test-issue-1080.js
  tests/jerry/regression-test-issue-783.js
Labels: bug, ecma builtins

#2964 Use custom dispatcher for String.prototype routines
  jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
  jerry-core/ecma/builtin-objects/ecma-builtin-helpers.h
  jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.inc.h
Labels: binary size

#2965 Use custom dispatcher for Object.prototype routines
  jerry-core/ecma/builtin-objects/ecma-builtin-object-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-object-prototype.inc.h
Labels: binary size

#2966 Use custom dispatcher for Object routines
  jerry-core/ecma/builtin-objects/ecma-builtin-object.c
  jerry-core/ecma/builtin-objects/ecma-builtin-object.inc.h
Labels: binary size

#2967 Use custom dispatcher for Function.prototype routines
  jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.inc.h
Labels: binary size

#2968 Use custom dispatcher for Number.prototype routines
  jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.inc.h
Labels: binary size

#2978 Fix 'eval' checking in import/export statements.
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/ecma/operations/ecma-eval.c
  jerry-core/parser/js/js-parser-internal.h
  jerry-core/parser/js/js-parser-module.c
  jerry-core/parser/js/js-parser.c
  tests/jerry/es2015/regression-test-issue-2975.js
Labels: ES2015, bug

#2954 Refactor memory management
  docs/02.API-REFERENCE.md
  docs/10.EXT-REFERENCE-HANDLER.md
  docs/14.EXT-REFERENCE-HANDLE-SCOPE.md
  jerry-core/api/jerry.c
  jerry-core/ecma/base/ecma-gc.c
  jerry-core/ecma/base/ecma-gc.h
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/ecma/base/ecma-init-finalize.c
  jerry-core/include/jerryscript-core.h
  jerry-core/jcontext/jcontext.h
  jerry-core/jmem/jmem-allocator-internal.h
  jerry-core/jmem/jmem-allocator.c
  jerry-core/jmem/jmem-heap.c
  jerry-core/jmem/jmem-poolman.c
  jerry-core/jmem/jmem.h
  jerry-ext/handler/handler-gc.c
  tests/unit-core/test-api.c
  tests/unit-core/test-heap.c
  tests/unit-core/test-objects-foreach.c
  tests/unit-ext/test-ext-autorelease.c
  tests/unit-ext/test-ext-handle-scope-escape.c
  tests/unit-ext/test-ext-handle-scope-handle-prelist-escape.c
  tests/unit-ext/test-ext-handle-scope-handle-prelist.c
  tests/unit-ext/test-ext-handle-scope-nested.c
  tests/unit-ext/test-ext-handle-scope-remove.c
  tests/unit-ext/test-ext-handle-scope-root.c
  tests/unit-ext/test-ext-handle-scope.c
Labels: memory management

#2962 Optional arguments should advance the iterator in jerryx_arg_transform_optional
  jerry-ext/arg/arg-transform-functions.c
  tests/unit-ext/test-ext-arg.c
Labels: bug, jerry-ext

#2976 Resolve module paths relative to the current module
  docs/05.PORT-API.md
  jerry-core/api/jerry.c
  jerry-core/ecma/base/ecma-module.c
  jerry-core/ecma/builtin-objects/ecma-builtin-function.c
  jerry-core/include/jerryscript-port.h
  jerry-core/jcontext/jcontext.h
  jerry-core/lit/lit-magic-strings.inc.h
  jerry-core/parser/js/js-parser-internal.h
  jerry-core/parser/js/js-parser-module.c
  jerry-core/parser/js/js-parser-statm.c
  jerry-main/main-unix.c
  jerry-port/default/default-io.c
  targets/nuttx-stm32f4/jerry_main.c
  targets/nuttx-stm32f4/jerry_port.c
  targets/tizenrt-artik053/apps/jerryscript/jerry_main.c
  tests/jerry/es2015/module-export-02.js
  tests/jerry/es2015/module-export-03.js
  tests/jerry/es2015/module-export-05.js
  tests/jerry/es2015/module-export-06.js
  tests/jerry/es2015/module-import-01.js
  tests/jerry/es2015/module-import-02.js
  tests/jerry/es2015/module-import-03.js
  tests/jerry/es2015/module-import-04.js
  tests/jerry/fail/module-001.js
  tests/jerry/fail/module-002.js
  tests/jerry/fail/module-003.js
  tests/jerry/fail/module-004.js
  tests/jerry/fail/module-005.js
  tests/jerry/fail/module-007.js
  tests/jerry/fail/module-010.js
  tests/jerry/fail/module-014.js
  tests/jerry/fail/module-015.js
  tests/jerry/fail/module-016.js
  tests/jerry/fail/module-017.js
  tests/jerry/fail/module-018.js
  tests/jerry/fail/module-020.js
  tests/jerry/fail/module-021.js
  tests/jerry/fail/module-022.js
  tests/jerry/fail/module-023.js
  tests/jerry/fail/module-024.js
  tests/jerry/fail/module-025.js
  tests/jerry/fail/module-026.js
  tests/jerry/fail/module-027.js
  tests/jerry/fail/module-028.js
  tests/jerry/fail/module-029.js
  tests/jerry/fail/module-030.js
  tests/jerry/fail/regression-test-issue-2896.js
Labels: ES2015, jerry-port

#2979 Add dependency info for accessing memstats from API
  docs/02.API-REFERENCE.md
Labels: documentation

#2969 Rework the engine's internal recursion limit
  .travis.yml
  jerry-core/CMakeLists.txt
  jerry-core/config.h
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/ecma/base/ecma-helpers.c
  jerry-core/ecma/base/ecma-helpers.h
  jerry-core/ecma/base/ecma-init-finalize.c
  jerry-core/ecma/operations/ecma-function-object.c
  jerry-core/ecma/operations/ecma-regexp-object.c
  jerry-core/ecma/operations/ecma-regexp-object.h
  jerry-core/jcontext/jcontext.h
  jerry-core/parser/regexp/re-compiler.c
  jerry-core/parser/regexp/re-compiler.h
  jerry-core/vm/vm.c
  tests/jerry/regression-test-issue-2190.js
  tests/jerry/regression-test-issue-2258-2963.js
  tests/jerry/regression-test-issue-2448.js
  tests/jerry/stack-limit.js
  tools/build.py
  tools/run-tests.py
Labels: enhancement

#2977 Add documentation for configuration options
  docs/00.GETTING-STARTED.md
  docs/01.CONFIGURATION.md
  tools/update-webpage.sh
Labels: documentation

#2956 Add extra details for the api example page
  docs/03.API-EXAMPLE.md
Labels: documentation

#2925 Add keys, values, entires functions for typedArray
  jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c
  jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.inc.h
  jerry-core/lit/lit-magic-strings.inc.h
  tests/jerry/es2015/typedarray-prototype-entires.js
  tests/jerry/es2015/typedarray-prototype-keys.js
  tests/jerry/es2015/typedarray-prototype-values.js
Labels: ES2015

#2419 Migration Guide
  README.md
  docs/02.API-REFERENCE.md
  docs/16.MIGRATION-GUIDE.md
  tools/update-webpage.sh
Labels: documentation

#2988 Add Configuration doc to the README
  README.md
Labels: documentation

#2989 Improve single-source generation
  tools/srcgenerator.py
  tools/srcmerger.py
Labels: infrastructure

#2715 [Proposal] Introduce new jerry-ext methods to ease method/property registration
  docs/10.EXT-REFERENCE-HANDLER.md
  jerry-ext/handler/handler-register.c
  jerry-ext/include/jerryscript-ext/handler.h
  tests/unit-ext/test-ext-method-register.c
Labels: jerry-ext

#2992 Fix incorrect feature guard for class support
  jerry-core/ecma/base/ecma-helpers.c
Labels: ES2015, bug
