Repository jerryscript-project/jerryscript, pull requests merged in 2020-05, with the labels that each got.

#3681 Add value/key sign swap for Set.add and Map.set methods
  jerry-core/ecma/operations/ecma-container-object.c
  tests/jerry/es2015/map.js
  tests/jerry/es2015/set.js
Labels: ES2015

#3701 Added new target support in Map , WeakMap, Set and WeakSet
  jerry-core/api/jerry.c
  jerry-core/ecma/operations/ecma-container-object.c
  tests/jerry/es2015/new-target-for-containers.js
Labels: ES2015

#3704 Fix __proto__ parsing in object literals
  jerry-core/parser/js/byte-code.h
  jerry-core/parser/js/js-parser-expr.c
  jerry-core/vm/vm.c
  jerry-core/vm/vm.h
  tests/jerry/es2015/object-prototype-proto.js
Labels: bug, parser

#3709 Add missing index incrementation to ecma_builtin_string_object_raw
  jerry-core/ecma/builtin-objects/ecma-builtin-string.c
  tests/jerry/es2015/string-raw.js
Labels: bug

#3720 Fix fast array handling when doing put with receiver
  jerry-core/ecma/operations/ecma-objects.c
  tests/jerry/es2015/regression-test-issue-3715.js
Labels: bug

#3719 Fix appending elements for ecma collection
  jerry-core/ecma/base/ecma-helpers-collection.c
  tests/jerry/es2015/proxy_own_keys.js
  tests/jerry/regression-test-issue-3711.js
Labels: bug

#3676 Update the Array.prototype.reverse method to support ES6 version
  jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c
  tests/jerry/es2015/proxy_get.js
Labels: ES2015

#3685 Add Proxy support for JSON.stringify
  jerry-core/ecma/builtin-objects/ecma-builtin-json.c
  tests/jerry/es2015/json-stringify.js
Labels: ES2015

#3730 Fix apply receiver operation for Proxy objects
  jerry-core/ecma/operations/ecma-objects.c
  tests/jerry/es2015/proxy_set_apply_receiver.js
Labels: bug

#3702 Fix value release in ecma_builtin_regexp_dispatch_helper
  jerry-core/ecma/builtin-objects/ecma-builtin-regexp.c
  tests/jerry/es2015/regression-test-issue-3671.js
Labels: bug

#3747 Fix rounding in Number.prototype.toFixed
  jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c
  tests/jerry/number-prototype-to-fixed.js
Labels: bug, ecma builtins

#3759 Fix iterator closing in Promise all/race
  jerry-core/ecma/builtin-objects/ecma-builtin-promise.c
  tests/jerry/es2015/promise-all-iterator.js
  tests/jerry/es2015/promise-race-iterator.js
Labels: bug, ecma builtins

#3765 Fix releasing the pattern string in regexp
  jerry-core/ecma/operations/ecma-regexp-object.c
  tests/jerry/regression-test-issue-3748-3749.js
Labels: bug

#3769 Fix parseFloat for non-infinity values
  jerry-core/ecma/base/ecma-helpers-number.c
  tests/jerry/regression-test-issue-3761.js
Labels: bug

#3766 Fix regexp flag handling in case of regexp like object
  jerry-core/ecma/builtin-objects/ecma-builtin-regexp.c
  tests/jerry/es2015/regression-test-issue-3760.js
Labels: bug

#3781 Accessor functions should not have 'prototype' property
  jerry-core/ecma/operations/ecma-function-object.c
  tests/test262-es6-excludelist.xml
Labels: ES2015

#3775 Change the Reflect.ownKeys method's length property
  jerry-core/ecma/builtin-objects/ecma-builtin-reflect.inc.h
  tests/test262-es6-excludelist.xml
Labels: ES2015

#3780 Fix property order in lazy property listing for builtin/external functions
  jerry-core/ecma/operations/ecma-function-object.c
  jerry-core/ecma/operations/ecma-function-object.h
  jerry-core/ecma/operations/ecma-objects.c
  jerry-core/vm/opcodes.c
  tests/jerry/es2015/regression-test-issue-3606.js
Labels: ES2015, ecma builtins

#3782 Fix parseFloat input string length calculation
  jerry-core/ecma/base/ecma-helpers-number.c
  tests/jerry/regression-test-issue-3778.js
Labels: bug

#3694 Handle properties of builtin function separately from builtin objects
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/ecma/builtin-objects/ecma-builtins.c
  jerry-core/ecma/builtin-objects/ecma-builtins.h
  jerry-core/ecma/operations/ecma-objects.c
Labels: ecma builtins

#3789 Fix array length check in lastIndexOf
  jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c
  tests/jerry/regression-test-issue-3779.js
Labels: bug

#3768 Optimize Promise data structures.
  jerry-core/api/jerry.c
  jerry-core/ecma/base/ecma-gc.c
  jerry-core/ecma/operations/ecma-jobqueue.c
  jerry-core/ecma/operations/ecma-jobqueue.h
  jerry-core/ecma/operations/ecma-promise-object.c
  jerry-core/ecma/operations/ecma-promise-object.h
  jerry-core/jcontext/jcontext.h
  jerry-core/lit/lit-magic-strings.h
Labels: ecma builtins, enhancement

#3770 Rework the Reflect.defineProperty method
  jerry-core/ecma/builtin-objects/ecma-builtin-reflect.c
  jerry-core/ecma/operations/ecma-conversion.c
  tests/test262-es6-excludelist.xml
Labels: ES2015, bug

#3791 Get the typedArray's length property properly in Array.prototype.concat
  jerry-core/ecma/operations/ecma-objects.c
  tests/test262-es6-excludelist.xml
Labels: ES2015

#3774 Rework the Reflect.setPrototypeOf method
  jerry-core/ecma/builtin-objects/ecma-builtin-reflect.c
  tests/test262-es6-excludelist.xml
Labels: ES2015

#3771 Rework the Reflect.preventExtensions method
  jerry-core/ecma/builtin-objects/ecma-builtin-reflect.c
  tests/test262-es6-excludelist.xml
Labels: ES2015

#3794 Fix lazy property listing for [[Enumerate]]
  jerry-core/ecma/operations/ecma-objects.c
  tests/jerry/es2015/regression-test-issue-3784.js
Labels: bug

#3796 Add stack limit check to proxy operations
  .travis.yml
  jerry-core/ecma/operations/ecma-proxy-object.c
  tests/jerry/es2015/regression-test-issue-3785.js
Labels: bug

#3795 Fix incorrect assertion in parser_parse_for_statement_start
  jerry-core/parser/js/js-parser-statm.c
  tests/jerry/es2015/regression-test-issue-3751.js
Labels: bug

#3797 Improve property key query for Proxy objects
  jerry-core/ecma/operations/ecma-objects.c
  tests/jerry/es2015/proxy_own_keys.js
  tests/jerry/es2015/regression-test-issue-3787.js
Labels: ES2015, bug

#3793 Fix error handling in scanner in case of OOM
  jerry-core/parser/js/js-scanner.c
Labels: bug

#3805 Fix adding entries to the internal buffer of a Map object
  jerry-core/ecma/operations/ecma-container-object.c
Labels: bug, ecma builtins

#3745 Implement function name support for script functions and classes
  jerry-core/api/jerry-snapshot.c
  jerry-core/api/jerry.c
  jerry-core/config.h
  jerry-core/ecma/base/ecma-helpers.c
  jerry-core/ecma/base/ecma-helpers.h
  jerry-core/ecma/base/ecma-literal-storage.c
  jerry-core/ecma/base/ecma-literal-storage.h
  jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-function.c
  jerry-core/ecma/operations/ecma-eval.c
  jerry-core/ecma/operations/ecma-function-object.c
  jerry-core/ecma/operations/ecma-function-object.h
  jerry-core/include/jerryscript-snapshot.h
  jerry-core/jcontext/jcontext.h
  jerry-core/lit/lit-magic-strings.inc.h
  jerry-core/lit/lit-magic-strings.ini
  jerry-core/parser/js/byte-code.c
  jerry-core/parser/js/byte-code.h
  jerry-core/parser/js/js-lexer.h
  jerry-core/parser/js/js-parser-expr.c
  jerry-core/parser/js/js-parser-internal.h
  jerry-core/parser/js/js-parser-statm.c
  jerry-core/parser/js/js-parser.c
  jerry-core/parser/js/js-scanner-util.c
  jerry-core/vm/vm-defines.h
  jerry-core/vm/vm.c
  jerry-core/vm/vm.h
  tests/test262-es6-excludelist.xml
  tests/unit-core/test-snapshot.c
Labels: ES2015

#3809 Script classes should be skipped during 'name' property lazy instantiation
  jerry-core/ecma/operations/ecma-function-object.c
Labels: bug

#3810 Add support for builtin/builtin routine 'name' property
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/ecma/builtin-objects/ecma-builtin-array.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-arraybuffer.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-boolean.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-date.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-error.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-evalerror.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-function.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-number.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-object.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-promise.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-proxy.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-rangeerror.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-referenceerror.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-regexp.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-string.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-symbol.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-syntaxerror.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-typeerror.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtin-urierror.inc.h
  jerry-core/ecma/builtin-objects/ecma-builtins.c
  jerry-core/ecma/operations/ecma-function-object.c
  jerry-core/ecma/operations/ecma-function-object.h
  jerry-core/lit/lit-magic-strings.h
  jerry-core/vm/vm.c
  tests/jerry/es2015/function-name.js
  tests/test262-es6-excludelist.xml
Labels: ecma builtins

#3816 Fix error handling in SerializeJSONProperty
  jerry-core/ecma/builtin-objects/ecma-builtin-json.c
  tests/jerry/regression-test-issue-3813.js
Labels: bug, ecma builtins
