Repository jerryscript-project/jerryscript, pull requests merged in 2021-12, with the labels that each got.

#4838 Update Zephyr target to 2.7.0
  .github/workflows/gh-actions.yml
  targets/zephyr/CMakeLists.txt
  targets/zephyr/Makefile.travis
  targets/zephyr/Makefile.zephyr
  targets/zephyr/README.md
  targets/zephyr/docs/arduino_101.jpg
  targets/zephyr/src/Makefile
  targets/zephyr/src/jerry-module.c
  targets/zephyr/src/jerry-port.c
Labels: targets

#4820 Improve float number handling and conversion
  jerry-core/CMakeLists.txt
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/ecma/base/ecma-helpers-conversion.c
  jerry-core/ecma/base/ecma-helpers-number.c
  jerry-core/ecma/base/ecma-helpers-number.h
  jerry-core/ecma/base/ecma-helpers-string.c
  jerry-core/ecma/base/ecma-helpers-value.c
  jerry-core/ecma/base/ecma-helpers.h
  jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-date.c
  jerry-core/ecma/builtin-objects/ecma-builtin-helpers-sort.c
  jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
  jerry-core/ecma/builtin-objects/ecma-builtin-math.c
  jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-number.c
  jerry-core/ecma/builtin-objects/ecma-builtins.c
  jerry-core/ecma/operations/ecma-array-object.c
  jerry-core/ecma/operations/ecma-bigint.c
  jerry-core/ecma/operations/ecma-conversion.c
  jerry-core/ecma/operations/ecma-iterator-object.c
  jerry-core/ecma/operations/ecma-number-arithmetic.c
  jerry-core/ecma/operations/ecma-number-arithmetic.h
  jerry-core/ecma/operations/ecma-typedarray-object.c
  jerry-core/lit/lit-char-helpers.c
  jerry-core/lit/lit-char-helpers.h
  jerry-core/parser/js/js-lexer.c
  jerry-core/vm/opcodes-ecma-arithmetics.c
  tests/jerry/number-prototype-to-string.js
  tests/jerry/test_suite_15.js
  tests/unit-core/test-to-length.c
Labels: bug, ecma core, ecma builtins

#4811 Fix AsyncGeneratorPrototype routines 'this' argument validation
  jerry-core/ecma/builtin-objects/ecma-builtin-async-generator-prototype.c
  tests/jerry/es.next/function-async-gen1.js
  tests/test262-esnext-excludelist.xml
Labels: bug, hacktoberfest-accepted

#4845 Build fix after #4811
  jerry-core/ecma/builtin-objects/ecma-builtin-async-generator-prototype.c
Labels: critical

#4849 Prevent arguments object creation if 'arguments' function argument is present
  jerry-core/parser/js/js-scanner-util.c
  tests/jerry/es.next/arguments.js
Labels: bug, pre-scanner

#4850 Fix buffer overflow in string radix conversion
  jerry-core/ecma/base/ecma-helpers-conversion.c
  jerry-core/ecma/base/ecma-helpers-number.c
  tests/jerry/regression-test-issue-4850.js
Labels: bug

#4859 Add FEATURE_INIT_FINI support on Windows.
  docs/12.EXT-REFERENCE-MODULE.md
  jerry-ext/include/jerryscript-ext/module.h
  tools/run-tests.py
Labels: windows

#4840 Update detached arraybuffer handling
  jerry-core/api/jerryscript.c
  jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c
  jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray.c
  jerry-core/ecma/operations/ecma-arraybuffer-object.c
  jerry-core/ecma/operations/ecma-arraybuffer-object.h
  jerry-core/ecma/operations/ecma-dataview-object.c
  jerry-core/ecma/operations/ecma-typedarray-object.c
  jerry-core/vm/vm.c
  tests/test262-esnext-excludelist.xml
  tools/runners/run-test-suite-test262.py
Labels: test262

#4881 Use external string when raising error
  jerry-core/ecma/operations/ecma-exceptions.c
  jerry-core/ecma/operations/ecma-exceptions.h
  jerry-core/parser/js/js-parser.c
  tests/unit-core/test-to-integer.c
  tests/unit-core/test-to-length.c
Labels: memory consumption

#4899 Add stack-overflow check for Array.prototype.{flat, flatMap}
  .github/workflows/gh-actions.yml
  jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c
  tests/jerry/es.next/regression-test-issue-4890.js
Labels: stack-overflow

#4889 Fix object class check for builtin Atomics
  jerry-core/ecma/operations/ecma-objects.c
  tests/jerry/es.next/regression-test-issue-4884.js
Labels: bug

#4885 Fix invalid argument reference in Promise.all executor
  jerry-core/ecma/operations/ecma-promise-object.c
  tests/jerry/es.next/regression-test-issue-4871.js
Labels: bug

#4880 Fix class constructor as accessor check
  jerry-core/parser/js/js-parser-expr.c
  tests/jerry/es.next/regression-test-issue-4874.js
Labels: bug, parser

#4879 Fix typedarray validation in Atomics read_modify_write
  jerry-core/ecma/operations/ecma-atomics-object.c
  tests/jerry/es.next/regression-test-issue-4875.js
  tests/test262-esnext-excludelist.xml
Labels: bug

#4868 Adjust fast array growth
  jerry-core/ecma/operations/ecma-array-object.c
  jerry-core/ecma/operations/ecma-array-object.h
Labels: performance

#4878 Fix arrow function this binding resolving if environment record is present
  jerry-core/ecma/operations/ecma-function-object.c
  jerry-core/ecma/operations/ecma-lex-env.c
  jerry-core/vm/opcodes.c
  jerry-core/vm/vm.c
  tests/jerry/es.next/regression-test-issue-4872.js
  tests/jerry/es.next/regression-test-issue-4876.js
Labels: bug

#4877 Prevent stack-overflow in json internalize property
  .github/workflows/gh-actions.yml
  jerry-core/ecma/builtin-objects/ecma-builtin-json.c
  tests/jerry/regression-test-issue-4848.js
Labels: stack-overflow

#4867 Fix arguments object detection in non-complex param list
  jerry-core/parser/js/js-scanner-util.c
  tests/jerry/es.next/arguments.js
Labels: pre-scanner

#4835 Implement 'hasOwn' routine of Object object
  jerry-core/api/jerryscript.c
  jerry-core/ecma/builtin-objects/ecma-builtin-object-prototype.c
  jerry-core/ecma/builtin-objects/ecma-builtin-object.c
  jerry-core/ecma/builtin-objects/ecma-builtin-object.inc.h
  jerry-core/ecma/operations/ecma-objects.c
  jerry-core/ecma/operations/ecma-objects.h
  jerry-core/lit/lit-magic-strings.inc.h
  jerry-core/lit/lit-magic-strings.ini
  tests/jerry/es.next/object-hasown.js
  tests/test262-esnext-excludelist.xml
Labels: ES.next

#4886 Fix redeclaration related eval corner cases
  jerry-core/debugger/debugger.c
  jerry-core/ecma/base/ecma-globals.h
  jerry-core/jcontext/jcontext.h
  jerry-core/parser/js/js-parser-internal.h
  jerry-core/parser/js/js-scanner-util.c
  jerry-core/vm/vm.c
  tests/jerry/es.next/arguments.js
  tests/test262-esnext-excludelist.xml
Labels: parser

#4905 Minimize mbedos5 target
  .github/workflows/gh-actions.yml
  targets/os/mbedos5/.gitignore
  targets/os/mbedos5/.mbedignore
  targets/os/mbedos5/Makefile
  targets/os/mbedos5/Makefile.travis
  targets/os/mbedos5/README.md
  targets/os/mbedos5/jerry-main.cpp
  targets/os/mbedos5/jerry-port.cpp
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-drivers/AnalogIn-js.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-drivers/DigitalOut-js.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-drivers/I2C-js.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-drivers/InterruptIn-js.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-drivers/PwmOut-js.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-drivers/lib_drivers.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-drivers/setInterval-js.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-drivers/setTimeout-js.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-drivers/source/AnalogIn-js.cpp
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-drivers/source/DigitalOut-js.cpp
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-drivers/source/I2C-js.cpp
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-drivers/source/InterruptIn-js.cpp
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-drivers/source/PwmOut-js.cpp
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-drivers/source/setInterval-js.cpp
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-drivers/source/setTimeout-js.cpp
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-event-loop/BoundCallback.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-event-loop/EventLoop.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-event-loop/source/EventLoop.cpp
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-launcher/launcher.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-launcher/setup.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-launcher/source/launcher.cpp
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-launcher/source/setup.cpp
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-library-registry/registry.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-library-registry/source/registry.cpp
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-library-registry/source/wrap_tools.cpp
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-library-registry/wrap_tools.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-util/js_source.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-util/logging.h
  targets/os/mbedos5/jerryscript-mbed/jerryscript-mbed-util/wrappers.h
  targets/os/mbedos5/js/flash_leds.js
  targets/os/mbedos5/js/main.js
  targets/os/mbedos5/mbed-os.lib
  targets/os/mbedos5/mbed_app.json
  targets/os/mbedos5/tools/check_pins.sh
  targets/os/mbedos5/tools/cmsis.h
  targets/os/mbedos5/tools/generate_pins.py
  targets/os/mbedos5/tools/jshint.conf
  targets/os/mbedos5/tools/requirements.txt
Labels: targets

#4841 Implement ECMAScript 2022 class static block
  jerry-core/parser/js/byte-code.c
  jerry-core/parser/js/byte-code.h
  jerry-core/parser/js/js-lexer.c
  jerry-core/parser/js/js-parser-expr.c
  jerry-core/parser/js/js-parser-internal.h
  jerry-core/parser/js/js-parser-statm.c
  jerry-core/parser/js/js-parser.c
  jerry-core/parser/js/js-scanner-internal.h
  jerry-core/parser/js/js-scanner-util.c
  jerry-core/parser/js/js-scanner.c
  jerry-core/parser/js/js-scanner.h
  jerry-core/vm/vm.c
  jerry-core/vm/vm.h
  tests/jerry/es.next/class_static_block.js
  tests/test262-esnext-excludelist.xml
Labels: ES.next, test262
