Repository jerryscript-project/jerryscript, pull requests merged in 2022-01, with the labels that each got.

#4942 Fix class static block opening brace parsing
  jerry-core/parser/js/js-lexer.c
  tests/jerry/es.next/regression-test-issue-4916.js
Labels: bug, parser

#4945 Add stack-overflow check for general [[Construct]] method of function objects
  .github/workflows/gh-actions.yml
  jerry-core/ecma/operations/ecma-function-object.c
  tests/jerry/regression-test-issue-4901.js
Labels: stack-overflow

#4954 Add missing object types for ecma_object_get_class_name
  jerry-core/ecma/operations/ecma-objects.c
  tests/jerry/es.next/regression-test-issue-4937-4938.js
Labels: bug

#4955 Date.prototype.setYear should invalidate cached tza
  jerry-core/ecma/builtin-objects/ecma-builtin-date-prototype.c
  tests/jerry/es.next/regression-test-issue-4939-4940.js
Labels: bug

#4946 Fix invalid assertion CESU8-UTF8 buffer copy
  jerry-core/lit/lit-strings.c
  tests/jerry/fail/regression-test-issue-4920.js
Labels: bug

#4944 Fix memory leak in AtomicModifyWrite
  jerry-core/ecma/operations/ecma-atomics-object.c
  tests/jerry/es.next/regression-test-issue-4894.js
Labels: bug

#4952 Fix fast array objects cannot hold private properties
  jerry-core/vm/opcodes.c
  tests/jerry/es.next/regression-test-issue-4934.js
Labels: bug

#4951 Private identifier resolving should always construct new literal object
  jerry-core/parser/js/js-parser.c
  tests/jerry/es.next/regression-test-issue-4930.js
Labels: bug, parser

#4950 Check rest initializer existence after pattern finalization
  jerry-core/parser/js/js-parser-expr.c
  tests/jerry/es.next/regression-test-issue-4928.js
Labels: bug, parser

#4949 Fix async identifier parsing in class field position
  jerry-core/parser/js/js-scanner.c
  tests/jerry/es.next/regression-test-issue-4927.js
Labels: bug, pre-scanner

#4953 Add missing toObject conversion for PrivateSet operation
  jerry-core/vm/opcodes.c
  tests/jerry/es.next/regression-test-issue-4936.js
  tests/test262-esnext-excludelist.xml
Labels: bug

#4947 Fix duplicated private identifier lookup
  jerry-core/parser/js/js-parser-expr.c
  tests/jerry/es.next/private_fields.js
Labels: bug

#4971 Fix logging related issues
  jerry-core/CMakeLists.txt
  jerry-core/api/jerryscript.c
  jerry-core/jcontext/jcontext.h
  jerry-core/jmem/jmem-heap.c
  jerry-core/jrt/jrt-logging.c
  jerry-core/jrt/jrt.h
Labels: bug, ecma core
